name: PacketsTest
version: '${project.version}'
main: josscoder.packets.PacketsTest
author: Josscoder
description: A test plugin
depend: [ProtocolLib]
website: https://github.com/Josscoder/code-samples
